/* import Layout from "../components/Layout";
import Head from 'next/head' ok
import styles from '@/styles/Home.module.css'; ok */
import Head from 'next/head'
import styles from '@/styles/Home.module.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import Layout from '@/components/Layout';

export default function Contacto() {
    return (
        <>
            <Head>
                <title>To Do List</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <main>
                <Layout>
                    <div >
                        <h1>Este es el componente Contacto</h1>
                        <p>Este es un sitio de ejemplo</p>
                        <label for="email">email </label>
                        <input type='email'></input>
                        <label for="fname">First name: </label>
                        <input type="text" id="fname" name="fname"></input>
                    </div>
                </Layout>
                
            </main>

        </>

    );
}