import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import Layout from '@/components/Layout';
import React from "react";
import CustomButton from '@/components/button.js';
import CustomMain from '@/components/Main';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>To Do List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

      </Head>
      <main>

        <Layout >
          <div >
            <h1>Este es el componente home Bienvenido a mi sitio del Home index.js</h1>
            <p>Este es un sitio de ejemplo en el index.js</p>
          </div>
          <CustomMain title="Mi to do list" description="Bienvenido a mi to do list">
            <p>Aquí puedes agregar y completar tareas para mantenerte organizado.</p>
            <ul>
              <li>Comprar leche</li>
              <li>Hacer ejercicio</li>
              <li>Completar el proyecto de React</li>
            </ul>
          </CustomMain>
          <div>
            <CustomButton variant="success">
              Hola soy un boton
            </CustomButton>
            <CustomButton variant="danger">
              Yo tambien
            </CustomButton>
          </div>
        </Layout>



      </main>
    </>
  )
}
