import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import Boton from '@/components/button.js';
import Layout from '@/components/Layout';
import React from "react";
import Button from '@/components/button.js';
import Pepe from '@/components/button.js';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>To Do List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
      </Head>
      <main>

        <Layout >
          <div >
            <h1>Este es el componente home Bienvenido a mi sitio del Home index.js</h1>
            <p>Este es un sitio de ejemplo</p>
          </div>
        </Layout>
        <div>
          <Pepe />
        </div>



      </main>
    </>
  )
}
