import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import Layout from '@/components/Layout';

export default function Error404() {
    return (
        <>
            <Head>
                <title>To Do List</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <main>
                <Layout>
                    <div className={styles.container}>
                        <h1>Este es el error 404</h1>
                        <p>Este es un sitio no encontrado</p>
                    </div>
                </Layout>
            </main>

        </>

    );
}